package Blog::Tutorial::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Blog::Tutorial::DB',
    
    connect_info => {
        #dsn => 'dbi:Pg:dbname=blog_tutorial',
        dsn => 'dbi:Pg:dbname=blog_tutorial;host=localhost;port=5432',
        user => 'blog_user',
        password => 'blog_user123',
    }
);

=head1 NAME

Blog::Tutorial::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Blog::Tutorial>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Blog::Tutorial::DB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Vinícius Abrahão Bazana Schmidt

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
